services:
  mynginx-c:
    image: nginx:alpine-slim
    ports:
      - 880:80

    # method1
    #command: ['sh','-c', 'echo 1 ; echo 22']

    # method2
    command: |
      sh -c '
        echo 1 ; 
        echo 22 ;
      '
